X_PLACE = 'input_x_placeholder'
Y_PLACE = 'input_y_placeholder'
SAMPLE_WEIGHT_PLACE = 'input_sample_weight_place'
LR_PLACE = 'input_lr_placeholder'
WAVELET_DROPOUT_PLACE = 'input_wavelet_dropout_placeholder_with_default_0'
CONV_DROPOUT_PLACE = 'input_conv_dropout_placeholder_with_default_0'
DENSE_DROPOUT_PLACE = 'input_dropout_placeholder_with_default_0'

OP_INFERENCE = 'op_inference'
OP_LOSS = 'op_loss'
OP_TRAIN = 'op_train'
