from .wavelet_1d_2d_cnn_mlp import build_wavelet_1d_2d_cnn_mlp
from .conv_1d_densenet import build_conv_1d_dense_net
from .conv_1d_vgg import build_conv_1d_vgg
from .mfcc_2d_conv import build_mfcc_2d_conv
from .mfcc_2d_densenet import build_mfcc_2d_densenet
